### ISSUE TITLE
Manual installation not complete

### ISSUE THREAD

**Issue by erfjab** [H-Return/Hiddify-Manager-Bot#4]
سلام ریترن عزیز، امیدوارم حالت خوب باشه. احساس میکنم نصب دستی تکمیل نیست، یه نگاهی بنداز. موفق باشی 🙌🏻♥️

**Comment by H-Return** [comment]
سلام ممنون شماهم خوب باشی.
ممنون از نگاهت و دقتت❤️
درستش کردم🙏🏻
