### ISSUE TITLE
Not handling installation errors 

### ISSUE THREAD

**Issue by erfjab** [H-Return/Hiddify-Manager-Bot#5]
سلام ریترن عزیز، خسته نباشی.
فایل نصب رو بررسی میکردم که متوجه خطاهارو هندل نمیکنی، درسته احتمال ارور پایینه ولی بهتره خطاهارو هندل کنی تا هم کد متوقف بشه و با وجود ارور بات رو ران نکنه، ضمنا کاربر کامل متوجه بشه کجا ارور خورده که لاگ‌هاشو بخونه.... دمت گرم.

**Comment by erfjab** [comment]
اینم اضافه کنم که ورودی ها هم هندل نشده و در صورت ورود داده‌ی خالی یا اشتباه بات بازم اشتباه میره جلو.

**Comment by H-Return** [comment]
سلام عرفان جان امیدوارم خوب باشی.
درسته میگی عرفان جان من بیشتر این بات رو برای تست API نوشتم.
ولی حتما روی بات جدید که با ورژن 2 API سازگار سعی میکنم موقعه نصب و راه اندازی ارور هارو بیشتر هندل کنم.

**Comment by erfjab** [comment]
موفق باشی داداش 🙌🏻❤️
