### ISSUE TITLE
Change the bot library to aiogrom/telebot

### ISSUE THREAD

**Issue by erfjab** [H-Return/Hiddify-Manager-Bot#6]
سلام ریترن عزیز، خسته نباشی.
میخواستم سوال کنم که آیا برنامه ای برای تغییر کتابخانه‌ی بات داری؟ چون ptb با اینکه همیشه آپدیته ولی امکان توسعه پذیریش و ایجاد کامیونیتی توسعه‌ی بات رو عملا صفر می‌کند چون توسعه دهنده‌ی انگشت شماری بلده، در حالی که اون یکی کتابخانه ها مثل aio و telebot راحت متوجه و توسعه داده می‌شود.

**Comment by H-Return** [comment]
سلام عرفان جان.
من چون امکانات و به روز بودن Python telegram bot دیدم با این فریمورک نوشتم
ولی حتما یه نسخه با telebot هم می‌نویسم میزارم دیگه خودت ادامش بده ❤️
ایشو های ریپازیتوری بات ورژن جدید رو هم باز کردم یادم شده بود

سربلند باشی عزیز❤️
